name: MaChCMM
channels:
     - conda-forge
     - anaconda
     - defaults
     - rdkit
     - mordred-descriptor
dependencies:
- python=3.10.5
- ase==3.22.1
- openbabel==3.1.1
- pandas==1.4.3
- numpy==1.23.2
- rdkit==2022.03.5
- morfeus-ml==0.7.1
- mordred==1.2.0
- openpyxl
- pip
- pip:
  - libconeangle
  - epic-mace==0.4.0
  - chemplot
  - joblib
